apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-green
  labels:
    app: canary-app
    version: v2.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-app
      version: v2.0.0
  template:
    metadata:
      labels:
        app: canary-app
        version: v2.0.0
    spec:
      containers:
        - name: app
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
              command: ['/bin/sh', '-c']
              args: ['echo "<html><body><h1 style=\"color: green\">Version 2.0.0 (Green)</h1><p>Host: $(hostname)</p></body></html>" > /usr/share/nginx/html/index.html;
              exec nginx -g "daemon off;"
              ']
