apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # echo -n 'my-super-secret-password' | base64
  database.password: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk
  # echo -n 'my-api-key' | base64
  api.key: bXktYXBpLWtleQ==
