apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-lister-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pod-lister-sa
    namespace: default
  roleRef:
    kind: Role
    name: pod-lister-role
    apiGroup: rbac.authorization.k8s.io
