apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-probes
spec:
  selector:
    matchLabels:
      app: nginx-with-probes
  template:
    metadata:
      labels:
        app: nginx-with-probes
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
            livenessProbe:
              httpGet:
                path: /
                port: 80

              initialDelaySeconds: 5
              periodSeconds: 5
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 3
              periodSeconds: 5
              failureThreshold: 1
